name: jsonplaceholder_clean_architecture
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # Bloc for state management
  flutter_bloc: ^8.0.1
  stream_transform: ^2.0.0
  bloc_concurrency: ^0.2.0
  # Functional programming thingies
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.3
  # Service locator
  get_it: ^7.2.0
  # Remote API
  internet_connection_checker: ^0.0.1+3
  http: ^0.13.4
  # Local cache
  shared_preferences: ^2.0.13
  #for change App icon
  flutter_launcher_icons: "^0.9.2"


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/app-icon.png"



  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/icons/app-icon.png
